# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32540c85a7d9b30116e591fd6416c0492c7136e9d121ebc3062dd24ac662089dfc0e0d8f7b3bb8133fc56251949478404a6d8976f1bdc702dcd8433c00fc066c

test:
  secret_key_base: 40c6bb958b3e61b1e438b6295666477ec3e61d38f35ac46497dbe1ed364b1d59e838bdc849a660069afce8f1bfe037c28f2c903ff0de607aaf1309ca45a94f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
